import React, { useState, useMemo } from 'react';
import PropTypes from 'prop-types';
import { addLearner, deleteLearner, bulkDeleteLearners, updateLearner } from '../../api-client';
import { useNotification } from '../../context/NotificationContext';

const StudentsManagementModal = ({ isOpen, onClose, learners, loadData }) => {
  const { showNotification } = useNotification();
  const [showAddStudentForm, setShowAddStudentForm] = useState(false);
  const [newStudent, setNewStudent] = useState({
    firstName: '',
    lastName: '',
    className: '',
    gender: 'male'
  });
  const [selectedStudentIds, setSelectedStudentIds] = useState([]);
  const [isEditMode, setIsEditMode] = useState(false);
  const [studentFilters, setStudentFilters] = useState({
    search: '',
    class: '',
    gender: ''
  });

  const handleStudentFormSubmit = async (e) => {
    e.preventDefault();
    try {
      const studentData = {
        // ID number will be auto-generated by the API
        firstName: newStudent.firstName,
        lastName: newStudent.lastName,
        className: newStudent.className,
        gender: newStudent.gender
      };

      if (isEditMode) {
        // For edit mode, include the ID number
        studentData.idNumber = newStudent.idNumber;
        await updateLearner(studentData);
        showNotification({
          type: 'success',
          title: 'Success',
          message: 'Student details updated successfully!'
        });
      } else {
        // For add mode, ID is auto-generated
        const result = await addLearner(studentData);
        const generatedId = result.data.id_number;
        showNotification({
          type: 'success',
          title: 'Success',
          message: `Student added successfully with ID: ${generatedId}`
        });
      }

      setShowAddStudentForm(false);
      setIsEditMode(false);
      setNewStudent({ firstName: '', lastName: '', className: '', gender: 'male' });
      loadData();
    } catch (error) {
      console.error(`Error ${isEditMode ? 'updating' : 'adding'} student:`, error);
      showNotification({
        type: 'error',
        title: `${isEditMode ? 'Update' : 'Add'} Failed`,
        message: `Error ${isEditMode ? 'updating' : 'adding'} student: ${error.message}`
      });
    }
  };

  const handleDeleteStudent = async (studentId) => {
    try {
      await deleteLearner(studentId);
      loadData();
      showNotification({
        type: 'success',
        title: 'Success',
        message: 'Student deleted successfully!'
      });
    } catch (error) {
      console.error("Error deleting student:", error);
      showNotification({
        type: 'error',
        title: 'Delete Failed',
        message: `Error deleting student: ${error.message}`
      });
    }
  };

  const handleStartEdit = (student) => {
    setIsEditMode(true);
    setNewStudent({
      idNumber: student.id_number,
      firstName: student.first_name,
      lastName: student.last_name,
      className: student.class_name,
      gender: student.gender
    });
    setShowAddStudentForm(true);
  };

  const handleBulkDelete = async () => {
    if (selectedStudentIds.length === 0) {
      showNotification({
        type: 'warning',
        title: 'Selection Required',
        message: 'Please select students to delete.'
      });
      return;
    }

    try {
      await bulkDeleteLearners(selectedStudentIds);
      loadData();
      setSelectedStudentIds([]);
      showNotification({
        type: 'success',
        title: 'Success',
        message: 'Selected students deleted successfully!'
      });
    } catch (error) {
      console.error("Error bulk deleting students:", error);
      showNotification({
        type: 'error',
        title: 'Delete Failed',
        message: `Error deleting students: ${error.message}`
      });
    }
  };

  const filteredStudents = useMemo(() => {
    return learners.filter(student => {
      const searchLower = studentFilters.search.toLowerCase();
      const matchesSearch = !searchLower ||
        student.first_name?.toLowerCase().includes(searchLower) ||
        student.last_name?.toLowerCase().includes(searchLower) ||
        student.id_number?.toLowerCase().includes(searchLower) ||
        student.class_name?.toLowerCase().includes(searchLower);
      const matchesClass = !studentFilters.class || student.class_name === studentFilters.class;
      const matchesGender = !studentFilters.gender || student.gender === studentFilters.gender;
      return matchesSearch && matchesClass && matchesGender;
    });
  }, [learners, studentFilters]);

  const uniqueClasses = useMemo(() =>
    [...new Set(learners.map(s => s.class_name).filter(Boolean))].sort(),
    [learners]
  );

  const uniqueGenders = useMemo(() =>
    [...new Set(learners.map(s => s.gender).filter(Boolean))].sort(),
    [learners]
  );

  const handleFilterChange = (filterName, value) => {
    setStudentFilters(prev => ({ ...prev, [filterName]: value }));
  };

  const handleSelectStudent = (studentId) => {
    setSelectedStudentIds(prev =>
      prev.includes(studentId)
        ? prev.filter(id => id !== studentId)
        : [...prev, studentId]
    );
  };

  const handleSelectAll = (e) => {
    if (e.target.checked) {
      setSelectedStudentIds(filteredStudents.map(s => s.id_number));
    } else {
      setSelectedStudentIds([]);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/30 backdrop-blur-sm z-50 overflow-y-auto">
      <div className="flex items-center justify-center min-h-screen p-4">
        <div className="glass-card-golden rounded-lg p-6 w-full max-w-6xl my-8">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-2xl font-bold text-white">Students Management</h2>
            <button onClick={onClose} className="text-white/70 hover:text-white text-2xl">&times;</button>
          </div>

          <div className="mb-4 flex flex-wrap justify-between items-center gap-4">
            <button
              onClick={() => {
                setShowAddStudentForm(!showAddStudentForm);
                setIsEditMode(false);
                setNewStudent({ firstName: '', lastName: '', className: '', gender: 'male' });
              }}
              className="glass-button-primary text-white px-4 py-2 rounded-md"
            >
              {showAddStudentForm ? 'Cancel' : 'Add New Student'}
            </button>
            {selectedStudentIds.length > 0 && (
              <button
                onClick={handleBulkDelete}
                className="glass-button-danger text-white px-4 py-2 rounded-md"
              >
                Delete Selected ({selectedStudentIds.length})
              </button>
            )}
          </div>

          {/* Filters */}
          <div className="mb-4 glass rounded-lg p-4">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <input
                type="text"
                value={studentFilters.search}
                onChange={(e) => handleFilterChange('search', e.target.value)}
                placeholder="Search by name, ID, or class..."
                className="glass-input w-full px-3 py-2 rounded-md"
              />
              <select
                value={studentFilters.class}
                onChange={(e) => handleFilterChange('class', e.target.value)}
                className="glass-input w-full px-3 py-2 rounded-md"
              >
                <option value="">All Classes</option>
                {uniqueClasses.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
              <select
                value={studentFilters.gender}
                onChange={(e) => handleFilterChange('gender', e.target.value)}
                className="glass-input w-full px-3 py-2 rounded-md"
              >
                <option value="">All Genders</option>
                {uniqueGenders.map(g => <option key={g} value={g}>{g}</option>)}
              </select>
              <button
                onClick={() => setStudentFilters({ search: '', class: '', gender: '' })}
                className="glass-button w-full px-3 py-2 rounded-md"
              >
                Clear Filters
              </button>
            </div>
            <div className="mt-2 text-sm text-white/80">
              Showing {filteredStudents.length} of {learners.length} students
            </div>
          </div>

          {/* Add/Edit Student Form */}
          {showAddStudentForm && (
            <div className="mb-6 glass rounded-lg p-4">
              <h3 className="text-lg font-medium text-white mb-3">
                {isEditMode ? 'Edit Student' : 'Add New Student'}
              </h3>
              {!isEditMode && (
                <p className="text-sm text-blue-600 mb-3 bg-blue-50 p-2 rounded">
                  ℹ️ Student ID will be automatically generated (format: eSBA001, eSBA002, etc.)
                </p>
              )}
              <form onSubmit={handleStudentFormSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {isEditMode && (
                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-white/90 mb-1">Student ID</label>
                    <input
                      type="text"
                      value={newStudent.idNumber || ''}
                      className="glass-input w-full px-3 py-2 rounded-md bg-gray-100"
                      readOnly
                      disabled
                    />
                  </div>
                )}
                <input
                  type="text"
                  value={newStudent.firstName}
                  onChange={(e) => setNewStudent({...newStudent, firstName: e.target.value})}
                  className="glass-input w-full px-3 py-2 rounded-md"
                  placeholder="First Name"
                  required
                />
                <input
                  type="text"
                  value={newStudent.lastName}
                  onChange={(e) => setNewStudent({...newStudent, lastName: e.target.value})}
                  className="glass-input w-full px-3 py-2 rounded-md"
                  placeholder="Last Name"
                  required
                />
                <input
                  type="text"
                  value={newStudent.className}
                  onChange={(e) => setNewStudent({...newStudent, className: e.target.value})}
                  className="glass-input w-full px-3 py-2 rounded-md"
                  placeholder="Class (e.g., BS1, KG1)"
                  required
                />
                <select
                  value={newStudent.gender}
                  onChange={(e) => setNewStudent({...newStudent, gender: e.target.value})}
                  className="glass-input w-full px-3 py-2 rounded-md"
                >
                  <option value="male">Male</option>
                  <option value="female">Female</option>
                </select>
                <div className="md:col-span-2">
                  <button
                    type="submit"
                    className="glass-button-primary text-white px-4 py-2 rounded-md"
                  >
                    {isEditMode ? 'Save Changes' : 'Add Student'}
                  </button>
                </div>
              </form>
            </div>
          )}

          {/* Students Table */}
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-white/20">
              <thead className="bg-white/10">
                <tr>
                  <th className="px-6 py-3">
                    <input
                      type="checkbox"
                      onChange={handleSelectAll}
                      checked={filteredStudents.length > 0 && selectedStudentIds.length === filteredStudents.length}
                    />
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/90 uppercase">ID</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/90 uppercase">Name</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/90 uppercase">Class</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/90 uppercase">Gender</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/90 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white/5 divide-y divide-white/20">
                {filteredStudents.map((student) => (
                  <tr key={student.id_number} className="hover:bg-white/10">
                    <td className="px-6 py-4">
                      <input
                        type="checkbox"
                        checked={selectedStudentIds.includes(student.id_number)}
                        onChange={() => handleSelectStudent(student.id_number)}
                      />
                    </td>
                    <td className="px-6 py-4 text-sm text-white/70">{student.id_number}</td>
                    <td className="px-6 py-4 text-sm font-medium text-white">
                      {student.first_name} {student.last_name}
                    </td>
                    <td className="px-6 py-4 text-sm text-white/70">{student.class_name}</td>
                    <td className="px-6 py-4 text-sm text-white/70 capitalize">{student.gender}</td>
                    <td className="px-6 py-4 text-sm font-medium space-x-4">
                      <button
                        onClick={() => handleStartEdit(student)}
                        className="text-indigo-600 hover:text-indigo-900"
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => handleDeleteStudent(student.id_number)}
                        className="text-red-600 hover:text-red-900"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {filteredStudents.length === 0 && (
              <div className="text-center py-8 text-white/70">
                No students found matching your criteria.
              </div>
            )}
          </div>

          <div className="flex justify-end mt-6">
            <button onClick={onClose} className="glass-button px-4 py-2 rounded-md">Close</button>
          </div>
        </div>
      </div>
    </div>
  );
};

StudentsManagementModal.propTypes = {
  isOpen: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
  learners: PropTypes.array.isRequired,
  loadData: PropTypes.func.isRequired,
};

export default StudentsManagementModal;
